- hosts: localhost
  connection: local
  become: no
  vars:
    apt_packages:
      - { name: jq }
  tasks:
    # apt
    - name: apt-get でインストール
      apt: >
        name={{ item.name }}
        state={{ item.state | default('present') }}
        update_cache=yes
      with_items: '{{ apt_packages }}'

   # oh-my-zsh
    - name: oh-my-zsh のインストール
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
      args:
        creates: ~/.oh-my-zsh/
