- hosts: localhost
  connection: local
  become: yes
  vars:
    apt_packages:
      - { name: jq }
      - { name: golang }
      - { name: gnome-terminal }
      - { name: ruby-build }
      - { name: rbenv }
      - { name: vim }
      - { name: zsh }

      #- { name: nodejs }
      #- { name: npm }
      # sudo npm cache clean
      # sudo npm install -g n
      # sudo n stable
      # sudo n lts
      # sudo apt-get purge nodejs npm
  tasks:
    # apt
    - name: apt-get でインストール
      apt: >
        name={{ item.name }}
        state={{ item.state | default('present') }}
        update_cache=yes
      with_items: '{{ apt_packages }}'
